packages:
  - .

engineStrict: true
nodeVersion: 24.19.0
saveExact: true
minimumReleaseAge: 1440
autoInstallPeers: false
strictPeerDependencies: true
strictDepBuilds: true

allowBuilds:
  esbuild: true
  sharp: true
